import {vec3, vec4} from 'gl-matrix';
import Stats from 'stats-js';
import * as DAT from 'dat.gui';
import Icosphere from './geometry/Icosphere';
import Square from './geometry/Square';
import Cube from './geometry/Cube';
import OpenGLRenderer from './rendering/gl/OpenGLRenderer';
import Camera from './Camera';
import {setGL} from './globals';
import ShaderProgram, {Shader} from './rendering/gl/ShaderProgram';

import lambertVertSource from './shaders/lambert-vert.glsl?raw';
import lambertFragSource from './shaders/lambert-frag.glsl?raw';

// let icosphere: Icosphere;
// let square: Square;
let cube: Cube;

const startTime = performance.now();

function loadScene() {
  // icosphere = new Icosphere(vec3.fromValues(0, 0, 0), 1, controls.tesselations);
  // icosphere.create();
  // square = new Square(vec3.fromValues(0, 0, 0));
  // square.create();
  cube = new Cube(vec3.fromValues(0, 0, 0));
  cube.create();
}

// Define an object with application parameters and button callbacks
// This will be referred to by dat.GUI's functions that add GUI elements.
const controls = {
  // tesselations: 5,
  objectColor: "#ffffff",
  texSize: 64,
  cellSize: 3,
  distortion: 0.1,
  absorptionStrength: 7.0,
  forwardScatteringDensity: 5.0,
  step: 100,
  'Load Scene': loadScene, // A function pointer, essentially
};

function main() {
  // Initial display for framerate
  const stats = Stats();
  stats.setMode(0);
  stats.domElement.style.position = 'absolute';
  stats.domElement.style.left = '0px';
  stats.domElement.style.top = '0px';
  document.body.appendChild(stats.domElement);

  // get canvas and webgl context
  const canvas = <HTMLCanvasElement> document.getElementById('canvas');
  const gl = <WebGL2RenderingContext> canvas.getContext('webgl2');
  if (!gl) {
    alert('WebGL 2 not supported!');
  }
  // `setGL` is a function imported above which sets the value of `gl` in the `globals.ts` module.
  // Later, we can import `gl` from `globals.ts` to access it
  setGL(gl);
  
  // ========== Worley Noise ==========
  function hash3(x: number, y: number, z: number) {
    // The constants in this noise function are generated by AI
    const dot1 = x * 127.1 + y * 311.7 + z * 74.7;
    const dot2 = x * 269.5 + y * 183.3 + z * 246.1;
    const dot3 = x * 113.5 + y * 271.9 + z * 124.6;

    return [
      fract(Math.sin(dot1) * 43758.5453),
      fract(Math.sin(dot2) * 43758.5453),
      fract(Math.sin(dot3) * 43758.5453),
    ];
  }

  function fract(x: number) {
    return x - Math.floor(x);
  }

  function worleyCPU(x: number, y: number, z: number) {
    const cellX = Math.floor(x);
    const cellY = Math.floor(y);
    const cellZ = Math.floor(z);

    const localX = fract(x);
    const localY = fract(y);
    const localZ = fract(z);

    let minDistSq = Infinity;

    for (let dz = -1; dz <= 1; dz++) {
      for (let dy = -1; dy <= 1; dy++) {
        for (let dx = -1; dx <= 1; dx++) {
          const neighborX = cellX + dx;
          const neighborY = cellY + dy;
          const neighborZ = cellZ + dz;

          const neighborPoint = hash3(
            neighborX,
            neighborY,
            neighborZ
          );

          const px = dx + neighborPoint[0] - localX;
          const py = dy + neighborPoint[1] - localY;
          const pz = dz + neighborPoint[2] - localZ;

          const distSq = px * px + py * py + pz * pz;

          minDistSq = Math.min(minDistSq, distSq);
        }
      }
    }

    return 1 - Math.sqrt(minDistSq / 3);
  }

  function GenWorleyNoise(): WebGLTexture
  {
      const data = new Uint8Array(controls.texSize * controls.texSize * controls.texSize);

      for (let z = 0; z < controls.texSize; z++) {
          for (let y = 0; y < controls.texSize; y++) {
              for (let x = 0; x < controls.texSize; x++) {
                  const i = x + y * controls.texSize + z * controls.texSize * controls.texSize;

                  const nx = x / controls.texSize;
                  const ny = y / controls.texSize;
                  const nz = z / controls.texSize;

                  const value = worleyCPU(nx * controls.cellSize, ny * controls.cellSize, nz * controls.cellSize); // 0..1
                  data[i] = value * 255;
              }
          }
      }

      const tex = gl.createTexture();
      gl.bindTexture(gl.TEXTURE_3D, tex);

      gl.texImage3D(
          gl.TEXTURE_3D,
          0,
          gl.R8,
          controls.texSize,
          controls.texSize,
          controls.texSize,
          0,
          gl.RED,
          gl.UNSIGNED_BYTE,
          data
      );

      gl.texParameteri(gl.TEXTURE_3D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
      gl.texParameteri(gl.TEXTURE_3D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);

      gl.texParameteri(gl.TEXTURE_3D, gl.TEXTURE_WRAP_S, gl.REPEAT);
      gl.texParameteri(gl.TEXTURE_3D, gl.TEXTURE_WRAP_T, gl.REPEAT);
      gl.texParameteri(gl.TEXTURE_3D, gl.TEXTURE_WRAP_R, gl.REPEAT);

      return tex;
  }
  // ========== Worley Noise ==========

  // Initial call to load scene
  loadScene();

  const camera = new Camera(vec3.fromValues(0, 0, 5), vec3.fromValues(0, 0, 0));

  const renderer = new OpenGLRenderer(canvas);
  renderer.setClearColor(0.2, 0.2, 0.2, 1);
  gl.enable(gl.DEPTH_TEST);

  const lambert = new ShaderProgram([
    new Shader(gl.VERTEX_SHADER, lambertVertSource),
    new Shader(gl.FRAGMENT_SHADER, lambertFragSource),
  ]);
  lambert.setCloudProperties(controls.absorptionStrength, controls.forwardScatteringDensity, controls.step);
  lambert.setGeometryColor(vec4.fromValues(1, 1, 1, 1));
  lambert.setTexture(GenWorleyNoise())

  // Add controls to the gui
  const gui = new DAT.GUI();
  // gui.add(controls, 'tesselations', 0, 8).step(1).onChange(
  //   (newTess) => {
  //     icosphere = new Icosphere(vec3.fromValues(0, 0, 0), 1, newTess);
  //     icosphere.create();
  //   }
  // );
  gui.add(controls, 'texSize', 32, 128).step(16).onChange(
    (newSize) => {
      lambert.setTexture(GenWorleyNoise())
    }
  );
  gui.add(controls, 'cellSize', 1, 32).step(1).onChange(
    (newSize) => {
      lambert.setTexture(GenWorleyNoise())
    }
  );
  gui.add(controls, 'distortion', 0.0, 1.0).step(0.05).onChange(
    (newDistortion) => {
      lambert.setDistortion(newDistortion);
    }
  );
  gui.add(controls, 'absorptionStrength', 1, 10).step(0.1).onChange(
    (newStrength) => {
      lambert.setCloudProperties(newStrength, controls.forwardScatteringDensity, controls.step);
    }
  );
  gui.add(controls, 'forwardScatteringDensity', 1, 5).step(0.1).onChange(
    (newDensity) => {
      lambert.setCloudProperties(controls.absorptionStrength, newDensity, controls.step);
    }
  );
  gui.add(controls, 'step', 10, 100).step(1).onChange(
    (newStep) => {
      lambert.setCloudProperties(controls.absorptionStrength, controls.forwardScatteringDensity, newStep);
    }
  );
  gui.addColor(controls, 'objectColor').onChange(
    (newCol) => {
      let intCol = parseInt(newCol.slice(1), 16)
      let col = vec4.fromValues(
        ((intCol >> 16) & 255) / 255,
        ((intCol >> 8) & 255) / 255,
        (intCol & 255) / 255,
        1
      );
      lambert.setGeometryColor(col);
    }
  );
  gui.add(controls, 'Load Scene');

  // This function will be called every frame
  function tick() {
    camera.update();

    stats.begin();

    gl.viewport(0, 0, window.innerWidth, window.innerHeight);
    renderer.clear();
    
    lambert.setTime((performance.now() - startTime) / 1000); // In seconds

    renderer.render(camera, lambert, [
      // icosphere,
      // square,
      cube
    ]);

    stats.end();

    // Tell the browser to call `tick` again whenever it renders a new frame
    requestAnimationFrame(tick);
  }

  window.addEventListener('resize', function() {
    renderer.setSize(window.innerWidth, window.innerHeight);
    camera.setAspectRatio(window.innerWidth / window.innerHeight);
    camera.updateProjectionMatrix();
  }, false);

  renderer.setSize(window.innerWidth, window.innerHeight);
  camera.setAspectRatio(window.innerWidth / window.innerHeight);
  camera.updateProjectionMatrix();

  // Start the render loop
  tick();
}

main();
